theme: minima
title: Portfolio
description: High school student interested in engineering, design, and applied technology
author: Malek Salam
header_pages:
  - home.md
  - projects.md
sass: assets/css